//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeResResaver.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeResResaver.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add files.
        /// </summary>
        public static string Common_AddFiles {
            get {
                return ResourceManager.GetString("Common_AddFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add folders.
        /// </summary>
        public static string Common_AddFolders {
            get {
                return ResourceManager.GetString("Common_AddFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Common_Back {
            get {
                return ResourceManager.GetString("Common_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Common_Browse {
            get {
                return ResourceManager.GetString("Common_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Common_Clear {
            get {
                return ResourceManager.GetString("Common_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Common_Error {
            get {
                return ResourceManager.GetString("Common_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Common_Filter {
            get {
                return ResourceManager.GetString("Common_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files (*.*)|*.*.
        /// </summary>
        public static string Common_FilterAllFiles {
            get {
                return ResourceManager.GetString("Common_FilterAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Common_Next {
            get {
                return ResourceManager.GetString("Common_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Common_OK {
            get {
                return ResourceManager.GetString("Common_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove files.
        /// </summary>
        public static string Common_RemoveFiles {
            get {
                return ResourceManager.GetString("Common_RemoveFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serious Engine Resource resave tool.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning for references, please wait..
        /// </summary>
        public static string ParseReferencesDialog_Help {
            get {
                return ResourceManager.GetString("ParseReferencesDialog_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse references.
        /// </summary>
        public static string ParseReferencesDialog_Title {
            get {
                return ResourceManager.GetString("ParseReferencesDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Substring in rule #{0}..
        /// </summary>
        public static string RenameFilesDialog_EmptySubstringError {
            get {
                return ResourceManager.GetString("RenameFilesDialog_EmptySubstringError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set files&apos; new names according to listed rules. Every substring (which can be a regex) in original file name will be replaced with corresponding replacement string..
        /// </summary>
        public static string RenameFilesDialog_Help {
            get {
                return ResourceManager.GetString("RenameFilesDialog_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore case.
        /// </summary>
        public static string RenameFilesDialog_IgnoreCase {
            get {
                return ResourceManager.GetString("RenameFilesDialog_IgnoreCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add renaming rules..
        /// </summary>
        public static string RenameFilesDialog_NoRulesError {
            get {
                return ResourceManager.GetString("RenameFilesDialog_NoRulesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex.
        /// </summary>
        public static string RenameFilesDialog_Regex {
            get {
                return ResourceManager.GetString("RenameFilesDialog_Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement.
        /// </summary>
        public static string RenameFilesDialog_Replacement {
            get {
                return ResourceManager.GetString("RenameFilesDialog_Replacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substring.
        /// </summary>
        public static string RenameFilesDialog_Substring {
            get {
                return ResourceManager.GetString("RenameFilesDialog_Substring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename files.
        /// </summary>
        public static string RenameFilesDialog_Title {
            get {
                return ResourceManager.GetString("RenameFilesDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check selected files.
        /// </summary>
        public static string ResaveFilesPage_CheckSelected {
            get {
                return ResourceManager.GetString("ResaveFilesPage_CheckSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint: double click Original name column cell to copy path.
        /// </summary>
        public static string ResaveFilesPage_CopyHint {
            get {
                return ResourceManager.GetString("ResaveFilesPage_CopyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete original.
        /// </summary>
        public static string ResaveFilesPage_DeleteOriginal {
            get {
                return ResourceManager.GetString("ResaveFilesPage_DeleteOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: missing new name..
        /// </summary>
        public static string ResaveFilesPage_EmptyNewNameError {
            get {
                return ResourceManager.GetString("ResaveFilesPage_EmptyNewNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game directory.
        /// </summary>
        public static string ResaveFilesPage_GameDir {
            get {
                return ResourceManager.GetString("ResaveFilesPage_GameDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select game directory and add files for resaving..
        /// </summary>
        public static string ResaveFilesPage_Help {
            get {
                return ResourceManager.GetString("ResaveFilesPage_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid game directory..
        /// </summary>
        public static string ResaveFilesPage_InvalidGameDirError {
            get {
                return ResourceManager.GetString("ResaveFilesPage_InvalidGameDirError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original name.
        /// </summary>
        public static string ResaveFilesPage_Name {
            get {
                return ResourceManager.GetString("ResaveFilesPage_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New name.
        /// </summary>
        public static string ResaveFilesPage_NewName {
            get {
                return ResourceManager.GetString("ResaveFilesPage_NewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: new name cannot be the same as old name..
        /// </summary>
        public static string ResaveFilesPage_NewNameEqualsToOldNameError {
            get {
                return ResourceManager.GetString("ResaveFilesPage_NewNameEqualsToOldNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add files for resaving..
        /// </summary>
        public static string ResaveFilesPage_NoFilesError {
            get {
                return ResourceManager.GetString("ResaveFilesPage_NoFilesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename selected files.
        /// </summary>
        public static string ResaveFilesPage_RenameFiles {
            get {
                return ResourceManager.GetString("ResaveFilesPage_RenameFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncheck selected files.
        /// </summary>
        public static string ResaveFilesPage_UncheckSelected {
            get {
                return ResourceManager.GetString("ResaveFilesPage_UncheckSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string ResavePage_AbortButton {
            get {
                return ResourceManager.GetString("ResavePage_AbortButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to start.
        /// </summary>
        public static string ResavePage_BackToStart {
            get {
                return ResourceManager.GetString("ResavePage_BackToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error message.
        /// </summary>
        public static string ResavePage_ErrorMessage {
            get {
                return ResourceManager.GetString("ResavePage_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string ResavePage_File {
            get {
                return ResourceManager.GetString("ResavePage_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game title.
        /// </summary>
        public static string ResavePage_GameTitle {
            get {
                return ResourceManager.GetString("ResavePage_GameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select game title and start resaving. Any encountered errors will be displayed in the table..
        /// </summary>
        public static string ResavePage_Help {
            get {
                return ResourceManager.GetString("ResavePage_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string ResavePage_StartButton {
            get {
                return ResourceManager.GetString("ResavePage_StartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborted.
        /// </summary>
        public static string ResavePage_StatusAborted {
            get {
                return ResourceManager.GetString("ResavePage_StatusAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string ResavePage_StatusFinished {
            get {
                return ResourceManager.GetString("ResavePage_StatusFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished with errors.
        /// </summary>
        public static string ResavePage_StatusFinishedWithErrors {
            get {
                return ResourceManager.GetString("ResavePage_StatusFinishedWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resaving files {0}/{1}.
        /// </summary>
        public static string ResavePage_StatusResaving {
            get {
                return ResourceManager.GetString("ResavePage_StatusResaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Start.
        /// </summary>
        public static string ResavePage_StatusStart {
            get {
                return ResourceManager.GetString("ResavePage_StatusStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating references {0}/{1}.
        /// </summary>
        public static string ResavePage_StatusUpdatingReferences {
            get {
                return ResourceManager.GetString("ResavePage_StatusUpdatingReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add files to update references to resaved files. Only files with references to resaved files will be added to the list. Resaved files update references themselves and do not need to be added here..
        /// </summary>
        public static string UpdateReferencesInFilesPage_Help {
            get {
                return ResourceManager.GetString("UpdateReferencesInFilesPage_Help", resourceCulture);
            }
        }
    }
}
